blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ General Question
    url: https://github.com/softeem-emphasis/Shridhan-content/discussions
    about: Ask questions or discuss ideas in GitHub Discussions
